using System.Security.Cryptography;
using System.Text;
using System.Text.Json.Serialization;

namespace EF.Blockchain.Domain;

/// <summary>
/// Represents a transaction on the blockchain, containing inputs, outputs, and metadata.
/// </summary>
public class Transaction
{
    /// <summary>
    /// Type of the transaction (e.g., REGULAR or FEE).
    /// </summary>
    public TransactionType Type { get; private set; }

    /// <summary>
    /// Timestamp in milliseconds when the transaction was created.
    /// </summary>
    public long Timestamp { get; private set; }

    /// <summary>
    /// Unique hash of the transaction.
    /// </summary>
    public string Hash { get; private set; }

    /// <summary>
    /// List of inputs that reference previous unspent outputs.
    /// </summary>
    public List<TransactionInput>? TxInputs { get; private set; }

    /// <summary>
    /// List of outputs generated by this transaction.
    /// </summary>
    public List<TransactionOutput> TxOutputs { get; private set; }

    /// <summary>
    /// Constructor used for JSON deserialization.
    /// </summary>
    [JsonConstructor]
    public Transaction(
        TransactionType type,
        long timestamp,
        string hash,
        List<TransactionInput>? txInputs = null,
        List<TransactionOutput>? txOutputs = null)
    {
        Type = type;
        Timestamp = timestamp;
        Hash = hash;
        TxInputs = txInputs;
        TxOutputs = txOutputs;
    }

    /// <summary>
    /// Creates a new transaction with optional parameters. Automatically computes the hash and sets output references.
    /// </summary>
    public Transaction(
        TransactionType? type = null,
        long? timestamp = null,
        List<TransactionInput>? txInputs = null,
        List<TransactionOutput>? txOutputs = null)
    {
        Type = type ?? TransactionType.REGULAR;
        Timestamp = timestamp ?? DateTimeOffset.UtcNow.ToUnixTimeMilliseconds();
        TxInputs = txInputs;
        TxOutputs = txOutputs ?? new List<TransactionOutput>();

        Hash = GetHash();

        // Set tx reference hash for outputs
        foreach (var txo in TxOutputs)
        {
            txo.SetTx(Hash);
        }
    }

    /// <summary>
    /// Calculates the SHA-256 hash of the transaction.
    /// </summary>
    /// <returns>The hex-encoded lowercase hash string.</returns>
    public string GetHash()
    {
        var from = TxInputs != null && TxInputs.Any()
            ? string.Join(",", TxInputs.Select(txi => txi.Signature))
            : "";

        var to = TxOutputs != null && TxOutputs.Any()
            ? string.Join(",", TxOutputs.Select(txo => txo.GetHash()))
            : "";

        var raw = $"{Type}{from}{to}{Timestamp}";
        using var sha256 = SHA256.Create();
        var bytes = Encoding.UTF8.GetBytes(raw);
        var hashBytes = sha256.ComputeHash(bytes);
        return Convert.ToHexString(hashBytes).ToLower();
    }

    /// <summary>
    /// Calculates the fee of the transaction (input sum - output sum).
    /// </summary>
    /// <returns>The fee amount.</returns>
    public int GetFee()
    {
        if (TxInputs == null || !TxInputs.Any())
            return 0;

        var inputSum = TxInputs.Sum(txi => txi.Amount);
        var outputSum = TxOutputs?.Sum(txo => txo.Amount) ?? 0;

        return inputSum - outputSum;
    }

    /// <summary>
    /// Validates the transaction, checking signatures, input/output consistency, hash integrity, and reward logic.
    /// </summary>
    /// <param name="difficulty">Blockchain difficulty at the time.</param>
    /// <param name="totalFees">Total fees collected for this block.</param>
    /// <returns>A <see cref="Validation"/> result indicating if the transaction is valid.</returns>
    public Validation IsValid(int difficulty, int totalFees)
    {
        if (Hash != GetHash())
            return new Validation(false, "Invalid hash");

        if (TxOutputs == null || !TxOutputs.Any() || TxOutputs.Any(txo => !txo.IsValid().Success))
            return new Validation(false, "Invalid TXO");

        if (TxInputs != null && TxInputs.Any())
        {
            var inputValidation = TxInputs
                .Select(txi => txi.IsValid())
                .Where(v => !v.Success)
                .ToList();

            if (inputValidation.Any())
            {
                var message = string.Join(" ", inputValidation.Select(v => v.Message));
                return new Validation(false, $"Invalid tx: {message}");
            }

            var inputSum = TxInputs.Sum(txi => txi.Amount);
            var outputSum = TxOutputs.Sum(txo => txo.Amount);
            if (inputSum < outputSum)
                return new Validation(false, "Invalid tx: input amounts must be equals or greater than outputs amounts");
        }

        if (TxOutputs.Any(txo => txo.Tx != Hash))
            return new Validation(false, "Invalid TXO reference hash");

        if (Type == TransactionType.FEE)
        {
            var txo = TxOutputs[0];
            if (txo.Amount > Blockchain.GetRewardAmount(difficulty) + totalFees)
                return new Validation(false, "Invalid tx reward");
        }

        return new Validation();
    }

    /// <summary>
    /// Creates a special transaction that represents a mining reward (fee transaction).
    /// </summary>
    /// <param name="txo">The output that represents the reward to the miner.</param>
    /// <returns>A fee-type transaction.</returns>
    public static Transaction FromReward(TransactionOutput txo)
    {
        var tx = new Transaction(
            type: TransactionType.FEE,
            txOutputs: new List<TransactionOutput> { txo }
        );

        tx.Hash = tx.GetHash();
        tx.TxOutputs[0].SetTx(tx.Hash);
        return tx;
    }
}
